#ifndef GLOBALS_H // header guard
#define GLOBALS_H

#define MAX_ROW 3
#define MAX_COL 3
#define PLAYER_ONE_GRID_MARKER 1
#define PLAYER_TWO_GRID_MARKER -1
#define CROSS_SYMBOL PLAYER_ONE_GRID_MARKER
#define NOUGHT_SYMBOL PLAYER_TWO_GRID_MARKER 
#define SERVER_MESSAGE_CODE_LENGTH 1 //server message code is in integer value which should be prepended to all server->client messages 
#define SERVER_MESSAGE_LENGTH (MAX_ROW*MAX_COL) + SERVER_MESSAGE_CODE_LENGTH 
#define SERVER_MESSAGE_LENGTH_BYTES sizeof(int)*(SERVER_MESSAGE_LENGTH)
#define WINNING_SCORE MAX_COL
#define PORT "3490"

typedef enum ServerMessageCode{
    SERVER_MESSAGE_CODE_INVALID = -1,
    SERVER_MESSAGE_CODE_WAITING_FOR_OPPONENT,
    SERVER_MESSAGE_CODE_OPPONENT_DISSCONNECTED,
    SERVER_MESSAGE_CODE_GAME_DATA_UPDATE,
    SERVER_MESSAGE_CODE_GAME_OVER_WIN,
    SERVER_MESSAGE_CODE_GAME_OVER_LOSS,
    SERVER_MESSAGE_CODE_GAME_OVER_DRAW
} ServerMessageCode;

typedef enum Bool{
    False,
    True
} Bool;
#endif // GLOBALS_H
